### PR TITLE
Add AppImage builder workflow

### PR DESCRIPTION
**Pull request by git-developer**
Follow-up of https://github.com/v1993/evdevhook2/pull/3

- [Branch Push](https://github.com/git-developer/linuxmotehook2/actions/runs/6100522212)
- [Tag Push](https://github.com/git-developer/linuxmotehook2/actions/runs/6100471504)
- [Release page](https://github.com/git-developer/linuxmotehook2/releases/tag/v0.1.5-1)

Would be great if you could provide a beautiful icon ;)

### CODE REVIEW

**Comment by v1993** [comment]
Calm down, I can only review so much stuff :upside_down_face:.

On a serious note, I'd appreciate if you incorporated my tweaks from https://github.com/v1993/evdevhook2/commit/acbc9379fdcb06afa132cc83286edfcca79f9202 into this PR.

I can't really promise a beautiful icon, but I'll look into making at least a decent-ish one.

**Comment by git-developer** [comment]
I incorporated `main` a few days ago, the only missing thing is an icon.

**Comment by git-developer** [comment]
I'm currently busy, but can have a look later on. Maybe an `after_bundle` script can be used to patch the desktop file ([docs](https://appimage-builder.readthedocs.io/en/latest/reference/recipe.html#section-scripts)).

**Comment by v1993** [comment]
@git-developer I've tried with hooks for various stages but wasn't able to affect the resulting desktop file. See https://github.com/v1993/evdevhook2/pull/5.

**Comment by v1993** [comment]
I'd appreciate if you ported recent changes to evdevhook2 appimage build process here. Also, https://github.com/v1993/evdevhook2/commit/eec133c6259327e66d41fcfd77bf12805dc82825.

**Comment by v1993** [comment]
Thanks a ton! Hoping to make an icon and get this merged tomorrow.

**Comment by git-developer** [comment]
> Also, [v1993/evdevhook2@eec133c](https://github.com/v1993/evdevhook2/commit/eec133c6259327e66d41fcfd77bf12805dc82825).

Including a single branch effectively excludes all tags. Is that on purpose?

**Comment by v1993** [comment]
> > Also, [v1993/evdevhook2@eec133c](https://github.com/v1993/evdevhook2/commit/eec133c6259327e66d41fcfd77bf12805dc82825).
> 
> Including a single branch effectively excludes all tags. Is that on purpose?

Definitely not. Thanks for catching that!

How about running on release instead of on all tags, though?

**Comment by git-developer** [comment]
I don't know if there's a way to find out whether the build trigger was the creation of a GitHub Release, and didn't find anything about it in the [docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions) either.

But if you plan to have more tags than releases, you can employ a [naming convention](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#patterns-to-match-branches-and-tags) to distinguish releases from other tags, e.g. `tags: "v[0-9]+.[0-9]+.[0-9]+"`.

**Comment by v1993** [comment]
Can't you simply use [`release`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release) (on published) as a workflow trigger?

**Comment by git-developer** [comment]
You're right, I read the wrong document. Something like this:

```yaml
on:
  pull_request:
  push:
    branches: main
  release:
    types: published
```

**Comment by git-developer** [comment]
I'd like to ask you to have a look at another [suggestion](https://github.com/git-developer/linuxmotehook2/pull/1/files), a refactoring that moves platform information from the build directory name into a dedicated `.env` file. It avoids that build output must be copied or moved. If you agree that this would be an improvement, I will add it to this PR.

**Comment by v1993** [comment]
I'm a bit skeptical about that - does documentation describe the location of `TARGET_APPDIR`? If yes - sure, go for it. If not, I wouldn't rely on something left unspecified. That said, even if it's left unspecified, I much prefer the new version, so with minor tweaks (and leaving a call to `mv`/`cp`) it's still much better than what is used now.

**Comment by git-developer** [comment]
Thanks for your feedback.

I found no "normative definition" of `AppDir` as default path for the AppDir directory, but the [docs](https://appimage-builder.readthedocs.io/en/latest/intro/tutorial.html#preparing-the-appdir) are full of `AppDir` examples and the [source code](https://github.com/AppImageCrafters/appimage-builder/blob/42d32f11496de43a9f6a9ada7882a11296e357ca/appimagebuilder/cli/argparse.py#L44) uses `AppDir` as default.

There's an argument `--appdir` to set a custom AppDir when running `appimage-builder`, this is what `TARGET_APPDIR` is set to. I thought I could use this arg to ensure defined behavior, but unfortunately the GitHub action has a [bug](https://github.com/AppImageCrafters/build-appimage/issues/7) that prevents setting it.

Thus I partly reverted my suggestion, using a separate build directory and moving the files. What "minor tweaks" do you have in mind?

**Comment by v1993** [comment]
Hey, just so that you know - I haven't forgotten about this PR, just had other personal issues to deal with recently. Hoping to get this done and merged soon.

Minor tweaks I've been speaking about were already implemented as part of your latest changes, so that is not a concern. I'd greatly appreciate if you would PR equivalent of two last commits to evdevhook2 in the meantime.

**Comment by v1993** [comment]
Sorry for sitting on this for so long! Add this icon and it'll be good to go.

linuxmotehook2

**Comment by git-developer** [comment]
No problem!

**Comment by git-developer** [comment]
Would be great if you could create a release at some time later on.

**Comment by v1993** [comment]
Sure, I'm planning on that! I just want to commit a few other changes first before making a new release.

**Comment by git-developer** [comment]
Great. No need to hurry, just wanted to be sure. Thanks!

**Pull request merged**
